language: java
jdk:
  - oraclejdk8
before_install:
  - ls
install: ./gradlew build

notifications:
  email:
    recipients:
      - ranevesmotox@gmail.com
      - rjesus@thoughtworks.com
    on_success: never
    on_failure: always